import Head from 'next/head';
import { auth } from '../firebase/clientApp';

export default function Home() {
  const signOut = () =>
    auth
      .signOut()
      .then(() => {
        console.log('User signed out.');
      })
      .catch((error) => {
        console.error(error);
      });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1 onClick={signOut} className='text-xl font-main font-bold cursor-pointer'>
        Hello World
      </h1>
    </>
  );
}
